# Generated by Django 2.2.1 on 2019-06-29 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_dss_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NDVI',
            new_name='NDVIMaps',
        ),
    ]
