# Generated by Django 2.2.1 on 2019-06-29 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_dss_app', '0002_auto_20190629_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NDVIMaps',
            new_name='NDVIMap',
        ),
    ]
