# Generated by Django 2.2.1 on 2019-06-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_dss_app', '0003_auto_20190629_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndvimap',
            name='path',
            field=models.CharField(max_length=250),
        ),
    ]
