# Generated by Django 2.2.1 on 2019-06-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_dss_app', '0004_auto_20190629_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndvimap',
            name='nir_path',
            field=models.CharField(default='None', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ndvimap',
            name='rgb_path',
            field=models.CharField(default='None', max_length=250),
            preserve_default=False,
        ),
    ]
