# Generated by Django 2.2.1 on 2019-08-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_dss_app', '0008_fieldvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldvisit',
            name='ndvi_map',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
