# Generated by Django 2.2.1 on 2019-08-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_dss_app', '0009_auto_20190801_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldvisit',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fieldvisit',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
