# Generated by Django 2.2.1 on 2019-08-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_dss_app', '0010_auto_20190801_0705'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NDVIMap',
        ),
        migrations.DeleteModel(
            name='NIRMap',
        ),
        migrations.DeleteModel(
            name='RGBMap',
        ),
    ]
