# Generated by Django 2.2.1 on 2019-08-01 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_dss_app', '0011_auto_20190801_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_plant_health', models.FloatField()),
                ('bad_plant_health', models.FloatField()),
                ('non_plants', models.FloatField()),
                ('ndvi_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_dss_app.FieldVisit')),
            ],
        ),
    ]
