# Generated by Django 2.2.1 on 2019-08-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_dss_app', '0012_planthealth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldvisit',
            name='ndvi_map',
        ),
        migrations.RemoveField(
            model_name='fieldvisit',
            name='nir_map',
        ),
        migrations.RemoveField(
            model_name='fieldvisit',
            name='rgb_map',
        ),
        migrations.RemoveField(
            model_name='fieldvisit',
            name='tile_location',
        ),
        migrations.AddField(
            model_name='fieldvisit',
            name='real_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
