# Generated by Django 2.2.1 on 2019-09-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_dss_app', '0015_auto_20190927_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planthealth',
            old_name='ndvi_map',
            new_name='project_name',
        ),
    ]
