# Generated by Django 2.2.1 on 2019-09-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_dss_app', '0016_auto_20190928_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planthealth',
            old_name='project_name',
            new_name='project_id',
        ),
    ]
